### ISSUE TITLE
Issue with Champollion output

### ISSUE THREAD

**Issue by smangham** [Orvid/Caprica#1]
v0.3 errors on compiling workshopnpcscript as output by the latest Champollion- it includes the construct `If (Self as Actor is companionactorscript)`.
It compiles fine if you add brackets to produce `If ((Self as Actor) is companionactorscript)`

**Comment by Orvid** [comment]
Fixed in https://github.com/Orvid/Champollion/commit/8fc631775aa34dabcd72b606fc31d500e9087c06, and released as [Champollion v1.0.5](https://github.com/Orvid/Champollion/releases/tag/v1.0.5).
