### ISSUE TITLE
Recompiling scripts generates duplicate property modifiers.

### ISSUE THREAD

**Issue by hairlessOrphan** [Orvid/Caprica#2]
If you decompile a .pex with Champollion and recompile the .psc with Caprica, properties generate duplicate modifiers:

Before:
bool Property OwnedByPlayer = False auto conditional
bool Property PlayerHasVisited auto conditional hidden

After:
bool Property OwnedByPlayer = False auto conditional conditional
bool Property PlayerHasVisited auto conditional hidden conditional hidden

**Comment by Orvid** [comment]
This should be fixed in v0.1.1.
