### ISSUE TITLE
Unhandled duplicate parameter syntax error 

### ISSUE THREAD

**Issue by skk50** [Orvid/Caprica#23]
CAPRICA.EXE (Cmake#17 Master:6346694835) unhandled syntax error:

Debug.Trace("Scriptname.FunctionName.Content", aiSeverity=0, aiSeverity=0)
 
Importing files...
Imported 4560 files.
WARNING: Loose input files are assumed as being in the root namespace.
Adding file 'SKK_ConsoleUtilityScript.psc' to namespace ''.
Compiling SKK_ConsoleUtilityScript.psc
Press any key to continue . . .

No compile warnings or unexpected token errors.

**Comment by Orvid** [comment]
This should now produce a useful error message after https://github.com/Orvid/Caprica/commit/6378be5d26c19fb9bf684e4eef99a5b80c22f52e
