### ISSUE TITLE
Fatal Error: Unable to resolve type 'Quest'!

### ISSUE THREAD

**Issue by Sp0ckrates** [Orvid/Caprica#26]
Hi. Thank you for this build!  

_Fatal Error: Unable to resolve type 'Quest'!_

I'm getting the error when trying to create the pex using a psc created by Champollion for an existing game script.

I'm using the latest Champollion from here: https://www.nexusmods.com/starfield/mods/4528
I'm also using the Papyrus decompile and Compile Command Files from here: https://www.nexusmods.com/starfield/mods/3921

**Comment by nikitalita** [comment]
We don't provide support for the command files. It looks like it's failing to import the decompiled Starfield folder, but I don't know how the command files work and why it's not doing that.

**Comment by nikitalita** [comment]
We don’t provide support for the command files.
