### ISSUE TITLE
Forced casting generates errors

### ISSUE THREAD

**Issue by hairlessOrphan** [Orvid/Caprica#3]
Decompiling a script with Champollion and recompiling it with Caprica inserts forced casting (explicit coercion) in a bunch of places (variable as bool, variable as float, etc...). Just noticed you mentioned this already, so editing this ticket. The explicit coercion appears to be generating errors.

1) Enable logging (so can see the stack traces)
in Fallout.ini, under [Papyrus]:
bEnableLogging=1
bEnableTrace=1
bLoadDebugInformation=1

2) Decompile workshopscript.pex in Champollion and recompile the resulting workshopscript.psc

3) Go to a Settlement, and move a Settler to another Settlement
or
3) Find an idle companion at a Settlement, ask him/her to join you, then dismiss him/her to a different Settlement

4) errors are generated in \Documents\My Games\Fallout 4\Logs\Script\

(note that the vanilla script generates a couple of warnings and errors on its own, but recompiling generates a bunch of new ones that appear to be casting related)

**Comment by Orvid** [comment]
Which version of Caprica? There have been some recent improvements to the implicit casting that was being done.

**Comment by hairlessOrphan** [comment]
v0.1.0. I've been grabbing the latest from Nexus.

**Comment by Orvid** [comment]
This should be fixed in v0.1.1.
