### ISSUE TITLE
Script Wide Variables issue

### ISSUE THREAD

**Issue by KarmaPenny** [Orvid/Caprica#4]
It appears that using script wide variables causes the script to not function. It compiles without error but when called in game will not perform any action.

You can actually de-compile a working vanilla script that contains a script wide variable then recompile it without making any changes and it will no longer function.

Here is an example that compiles but does not function
```Papyrus
const ScriptName Broken extends ObjectReference

;-- Script Wide Variables ---------------------------------------
int test = 0

Function OnInit()
	test = 5
	Debug.Notification("This text never appears")
EndFunction
```

Remove the script wide variable and suddenly it does work
```Papyrus
const ScriptName Broken extends ObjectReference

Function OnInit()
	Debug.Notification("This text does appears")
EndFunction
```

**Comment by Orvid** [comment]
Do you have the specific script you were encountering this issue in? There should be no issues with it, but you are using a `const` on the `ScriptName` value, which I don't actually know the use of at the moment.

**Comment by SilverIce** [comment]
Maybe *const* means immutable script instance? Then it's not weird as `test = 5` attempts to modify it, but I doubt if the code should be compile-able

**Comment by KarmaPenny** [comment]
I'll create an example mod for you when I get a chance.

**Comment by KarmaPenny** [comment]
Going to be out of town this weekend so probably won't be until next week

**Comment by KarmaPenny** [comment]
Hmm actually I just tried things without that const flag and it appears to
be working. Sorry about that. The const flag came from one of the vanilla
scripts I copied and I didn't notice it at all.

**Comment by Orvid** [comment]
Well, if I was letting you compile without errors then that's an issue, I'll check and see what adding that as an error does.

**Comment by Orvid** [comment]
Trying to do this will now produce an error when you try to assign to a value on a const script.
