### ISSUE TITLE
No Disk Error

### ISSUE THREAD

**Issue by missionfloyd** [Orvid/Caprica#8]
It seems that if there's a G:\ drive with no disk in it (in my case, a card reader), this error pops up endlessly until I stop Caprica with Ctrl-C/

![untitled](https://cloud.githubusercontent.com/assets/4073789/14234810/c5f39c6a-f9a9-11e5-90fb-dc8b125854c1.png)

I'm simply dropping a script on Caprica.exe (version 0.1.5) after having set the import folder containing the extracted Fallout 4 scripts in caprica.cfg

I've tried this with three different computers, and they all do this if there's an empty G drive. If there's a disk in G, or if it's removed or disabled, it works fine.

All the stock Fallout 4 scripts reference a G drive as their source. Perhaps that has something to do with it.

**Comment by Orvid** [comment]
This probably has to do with Boost trying to check if a file exists on a specific drive. This isn't a difficult fix, I just have to make sure to get all of the places it's used.
