### ISSUE TITLE
Structs

### ISSUE THREAD

**Issue by Ashnal** [Orvid/Caprica#9]
It seems that Caprica doesn't support Structs yet. Can you add this? I like Caprica's language extensions, but it's unfortunate that it doesn't support structs like Beth's compiler.

**Comment by Ashnal** [comment]
Nevermind. I tried to name a Struct I created "New" and apparently that's a keyword of some kind ...

**Comment by Orvid** [comment]
New is the keyword used to create an instance of a struct or to create an array, so the error is expected if you try to name a struct `new`.
